name: Build Marp Slides

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build slides into docs/
        run: |
          mkdir -p docs
          for file in slides/*.md; do
            name=$(basename "$file" .md)
            marp "$file" --html --output "docs/$name.html"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: nyapp
          user_email: nyapp@users.noreply.github.com